let pokemonJson = [
        {id:1,
        name:'Bulbasaur',
        img:'images/bulbasaur.png', 
        type:'Grass | Poison', 
        sizes:'70cm',
        weak:'Fire | Psychic | Flying | Ice',
        description:'Bulbasaur (em japonês: ポカブ Fushigidane) é um Pokémon tipo Planta e Venenoso.',
        descModal:'Bulbasaur é uma criatura quadrúpede réptil que lembra um dinossauro jovem, com um azul-verde manchado. Ele tem três dedos brancos ou garras crescendo fora de suas quatro pernas, e seus olhos são de um vermelho brilhante. A característica mais notável deste Pokémon é o bulbo de cebola na sua parte traseira, que cresce de uma semente em suas costas plantada por sua mãe ao nascer.'},

        {id:2, 
        name:'Charmander', 
        img:'images/charmander.png', 
        type:'Fire', 
        sizes:'60cm',
        weak:'Water | Ground | Rock',
        description:'Charmander é um Pokémon lagarto do tipo fogo',
        descModal:'A chama que arde na ponta da sua cauda é uma indicação de suas emoções. A chama oscila quando Charmander está feliz. Se o Pokémon fica com raiva, a chama queima ferozmente.'},

        {id:3, 
        name:'Squirtle', 
        img:'images/squirtle.png', 
        type:'Water', 
        sizes:'60cm',
        weak:'Grass | Electric',
        description:'Squirtle é um Pokémon tartaruga pequena do tipo água',
        descModal:'O casco de Squirtle não é apenas usado para a proteção. A forma arredondada do casco e as ranhuras em sua superfície ajudam a minimizar a resistência na água, permitindo que este Pokémon nade em altas velocidades.'},

        {id:4, 
        name:'Caterpie', 
        img:'images/caterpie.png', 
        type:'Bug', 
        sizes:'30cm',
        weak:'Fire | Flying | Rock', 
        description:'Caterpie é um Pokémon lagarta do tipo inseto.',
        descModal:'Caterpie tem um apetite voraz. Ele pode devorar folhas maiores do que o próprio corpo bem diante dos seus olhos. A partir de sua antena, este Pokémon libera um odor terrivelmente forte.'},

        {id:5, 
        name:'Weedle', 
        img:'images/weedle.png', 
        type:'Bug | Poison', 
        sizes:'30cm',
        weak:'Psychic | Flying | Rock', 
        description:'Weedle é um Pokémon inseto peludo dos tipos veneno e inseto.',
        descModal: 'Weedle tem o sentido do faro extremamente aguçado. Ele é capaz de distinguir os seus tipos favoritos de folhas daqueles que não gosta apenas por cheirar com a sua grande probóscide (nariz) vermelha.'},

        {id:6, 
        name:'Pidgey', 
        img:'images/pidgey.png', 
        type:'Normal | Flying', 
        sizes:'30cm',
        weak:'Electric | Ice | Rock',
        description:'Pidgey é um Pokémon pássaro pequeno do tipo normal.',
        descModal:'Pidgey tem um senso de direção extremamente aguçado. Ele é capaz de infalivelmente voltar para casa para seu ninho, por mais longe que possa ser removido do seu ambiente familiar.'},

        {id:7, 
        name:'Rattata', 
        img:'images/rattata.png', 
        type:'Normal', 
        sizes:'30cm',
        weak:'Fighting',
        description:'Rattata é um Pokémon rato do tipo normal.',
        descModal:'Rattata é cauteloso ao extremo. Mesmo enquanto está dormindo, ele escuta constantemente movendo suas orelhas. Não é exigente sobre onde vive-ele vai fazer seu ninho em qualquer lugar.'},

        {id:8, 
        name:'Ekans', 
        img:'images/ekans.png', 
        type:'Poison', 
        sizes:'2.0m',
        weak:'Psychic | Ground',
        description:'Ekans é um Pokémon serpente do tipo veneno.',
        descModal:'Ekans enrola-se em uma espiral enquanto descansa. Assumir esta posição lhe permite responder rapidamente a uma ameaça de qualquer direção com um olhar de sua cabeça erguida.'},
        
        {id:9, 
        name:'Pikachu', 
        img:'images/pikachu.png', 
        type:'Electric', 
        sizes:'40cm',
        weak:'Ground',
        description:'Pikachu é um Pokémon rato do tipo elétrico.',
        descModal:'Sempre que Pikachu se depara com algo novo, ele o explode com um choque de eletricidade. Se você se deparar com um fruto enegrecido, é evidência de que esse Pokémon confundiu a intensidade de sua carga.'},
        
        {id:10, 
        name:'Clefairy', 
        img:'images/clefairy.png', 
        type:'Fairy', 
        sizes:'60cm',
        weak:'Steel | Poison',
        description:'Clefairy é um Pokémon fada do tipo fada.',
        descModal:'A cada noite de lua cheia, grupos deste Pokémon saem para brincar. Quando amanhece, os cansados Clefairy retornam ao seu refúgio nas montanhas tranquilos, e vão dormir aninhado-se uns contra os outros.'},

        {id:11, 
        name:'Vulpix', 
        img:'images/vulpix.png', 
        type:'Fire', 
        sizes:'60cm',
        weak:'Water | Ground | Rock',
        description:'Vulpix é um Pokémon raposa do tipo fogo.',
        descModal:'No momento de seu nascimento, Vulpix tem uma cauda branca. A cauda se separa em seis se este Pokémon recebe uma abundância de amor de seu treinador. As seis caudas tornam-se magnificamente enroladas.'},

        {id:12, 
        name:'Abra', 
        img:'images/abra.png', 
        type:'Psychic', 
        sizes:'90cm',
        weak:'Ghost | Dark | Bug',
        description:'Pikachu é um Pokémon rato do tipo elétrico.',
        descModal:'Sempre que Pikachu se depara com algo novo, ele o explode com um choque de eletricidade. Se você se deparar com um fruto enegrecido, é evidência de que esse Pokémon confundiu a intensidade de sua carga.'},

        {id:13, 
        name:'Slowpoke', 
        img:'images/slowpoke.png', 
        type:'Water | Psychic', 
        sizes:'1.20m',
        weak:'Ghost | Dark | Grass | Bug',
        description:'Slowpoke é um Pokémon dopado dos tipos água e psíquico.',
        descModal:'Slowpoke usa sua cauda para capturar suas presas mergulhando-a na água ao lado de um rio. No entanto, este Pokémon muitas vezes se esquece o que está fazendo e muitas vezes gasta todo o dia apenas descansando na beira da água.'},

        {id:14, 
        name:'Gengar', 
        img:'images/gengar.png', 
        type:'Ghost | Poison', 
        sizes:'1.50m',
        weak:'Ghost | Dark | Psychic',
        description:'Gengar é um Pokémon sombra dos tipos veneno e fantasma.',
        descModal:'Às vezes, em uma noite escura, a sua sombra projetada por um poste de repente e surpreendentemente ultrapassá-o. Isso na verdade é um Gengar correndo atrás de você, fingindo ser sua sombra.'},

        {id:15, 
        name:'Voltorb', 
        img:'images/voltorb.png', 
        type:'Electric', 
        sizes:'50cm',
        weak:'Ground',
        description:'Voltorb é um Pokémon bola do tipo elétrico.',
        descModal:'Voltorb foi avistado pela primeira vez em uma empresa que fabrica Pokébolas. A ligação entre essa observação e o fato de que este Pokémon é muito parecido com uma Pokébola permanece um mistério.'},

        {id:16, 
        name:'Onix', 
        img:'images/onix.png', 
        type:'Rock | Ground', 
        sizes:'8.80m',
        weak:'Steel | Water | Grass | Ice',
        description:'Onix é um Pokémon serpente de rocha dos tipos terra e pedra.',
        descModal:'Onix tem um ímã em seu cérebro. Ele atua como uma bússola para que esse Pokémon não perca a direção, enquanto estiver criando túneis. À medida que envelhece, o seu corpo torna-se cada vez mais redondo e polido.'},

        {id:17, 
        name:'Venonat', 
        img:'images/venonat.png', 
        type:'Bug | Poison', 
        sizes:'1.00m',
        weak:'Fire | Psychic | Flying',
        description:'Venonat é um Pokémon inseto dos tipos veneno e inseto.',
        descModal:'Diz-se que Venonat evoluiu de uma fina casca, com um pelo duro que cobre todo o corpo para sua proteção. Possui grandes olhos que nunca deixam de detectar até mesmo presas minúsculas.'},

        {id:18, 
        name:'Jigglypuff', 
        img:'images/jigglypuff.png', 
        type:'Fairy | Normal', 
        sizes:'50cm',
        weak:'Steel | Poison',
        description:'Jigglypuff é um Pokémon balão dos tipos normal e fada.',
        descModal:'As cordas vocais de Jigglypuff podem livremente ajustar o comprimento de onda da sua voz. Este Pokémon usa esta habilidade para cantar precisamente no comprimento de onda certo para tornar seus inimigos mais sonolentos.'},

        {id:19, 
        name:'Sandshrew', 
        img:'images/sandshrew.png', 
        type:'Ground', 
        sizes:'60cm',
        weak:'Water | Grass | Ice',
        description:'Sandshrew é um Pokémon rato do tipo terra.',
        descModal:'O corpo de Sandshrew está configurado para absorver a água sem desperdício, lhe permitindo sobreviver em um deserto árido. Este Pokémon se enrola para se proteger de seus inimigos.'},

        {id:20, 
        name:'Exeggcute', 
        img:'images/exeggcute.png', 
        type:'Grass | Psychic', 
        sizes:'40cm',
        weak:'Ghost | Fire | Ice | Dark',
        description:'Exeggcute é um Pokémon ovo dos tipos grama e psíquico.',
        descModal:'Este Pokémon consiste de seis ovos que formam um aglomerado. Os seis ovos atraem-se mutuamente e giram em círculos. Quando aparecem fissuras cada vez maiores sobre os ovos, Exeggcute está perto de evoluir.'},

        {id:21, 
        name:'Meowth', 
        img:'images/meowth.png', 
        type:'Normal', 
        sizes:'40cm',
        weak:'Fighting',
        description:'Meowth é um Pokémon gato arranhador do tipo normal.',
        descModal:'Meowth coloca pra fora suas garras afiadas em suas patas para se deslocar sorrateiramente por aí sem deixar quaisquer pegadas incriminatórias. Por alguma razão, este Pokémon ama moedas brilhantes que brilham na luz.'},






    ];